export const packages = {
  '@types/node': '^20.11.21',
  'ts-node': '^10.9.2',
  'tsconfig-paths': '^4.2.0',

  'react': '^18.2.0',
  'react-dom': '^18.2.0',
  '@types/react': '^18.2.64',

  'webpack': '^5.75.0',
  'webpack-cli': '^5.1.4',
  'webpack-dev-server': '^4.11.1',
  'copy-webpack-plugin': '^11.0.0',
  'html-webpack-plugin': '^5.5.0',
  'babel-loader': '^9.1.3',
  'css-loader': '^6.10.0',
  'postcss-loader': '^8.1.1',
  'postcss-preset-env': '^9.5.0',
  'sass-loader': '^14.1.1',
  'style-loader': '^3.3.4',
  'svg-inline-loader': '^0.8.2',
  'ts-loader': '^9.5.1',
  'tsconfig-paths-webpack-plugin': '^4.1.0',
  '@babel/preset-react': '^7.23.3',
  '@babel/preset-typescript': '^7.23.3',
  '@babel/preset-env': '^7.24.0',
  '@babel/cli': '^7.23.9',
  '@babel/core': '^7.24.0',

  'prettier': '^3.2.5',
  'child_process': '^1.0.2',
}

export const react_packages = ['react', 'react-dom', '@types/react']

export const webpack_packages = [
  'webpack',
  'webpack-cli',
  'webpack-dev-server',
  'copy-webpack-plugin',
  'html-webpack-plugin',
  'babel-loader',
  'css-loader',
  'postcss-loader',
  'postcss-preset-env',
  'sass-loader',
  'style-loader',
  'svg-inline-loader',
  'ts-loader',
  'tsconfig-paths-webpack-plugin',
  '@babel/preset-react',
  '@babel/preset-typescript',
  '@babel/preset-env',
  '@babel/cli',
  '@babel/core',
]
